name: Export & create release

on:
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y default-jdk default-jre
          sudo apt-get install -y jq
          sudo apt-get install -y software-properties-common xvfb libxrender1 libxtst6 libxi6
          sudo apt-get install -y libsdl2-2.0-0

      - name: Download & Install Processing
        run: |
          PROCESSING_DOWNLOAD_LINK="https://github.com/processing/processing4/releases/download/processing-1276-4.0b1/processing-4.0b1-linux64.tgz"
          PROCESSING_TAR_FILE="processing-4.0b1-linux64.tgz"
          cd ../../
          ls -l
          mkdir sketchbook
          mkdir sketchbook/libraries
          mkdir sketchbook/sketches
          wget --no-verbose --show-progress --progress=dot:mega $PROCESSING_DOWNLOAD_LINK
          tar -xvzf $PROCESSING_TAR_FILE
          rm $PROCESSING_TAR_FILE
          ls -l
          pwd

      - name: Download & install processing libraries
        run: |
          pwd
          ls -l
          HOME="$(pwd)"
          LIB_DIR=$HOME+"sketchbook/libraries"
          cd $LIB_DIR
          pwd
          cd $HOME
          pwd


