name: Export & create release (from linux)

on:
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y default-jdk default-jre
          sudo apt-get install -y jq
          sudo apt-get install -y software-properties-common xvfb libxrender1 libxtst6 libxi6
          sudo apt-get install -y libsdl2-2.0-0

      - name: Download & Install Processing
        run: |
          cd ../../
          ls -l
          PROCESSING_DOWNLOAD_LINK="https://github.com/processing/processing4/releases/download/processing-1276-4.0b1/processing-4.0b1-linux64.tgz"
          PROCESSING_TAR_FILE="processing-4.0b1-linux64.tgz"
          mkdir sketchbook
          mkdir sketchbook/libraries
          mkdir sketchbook/sketches
          wget --no-verbose --show-progress --progress=dot:mega $PROCESSING_DOWNLOAD_LINK
          tar -xvzf $PROCESSING_TAR_FILE
          rm $PROCESSING_TAR_FILE
          ls -l
          pwd

      - name: Download & install processing libraries
        run: |
          cd ../../
          ls -l
          HOME="$(pwd)"
          echo $HOME
          LIB_DIR=$HOME"/sketchbook/libraries"
          wget -O $LIB_DIR/video.zip https://github.com/processing/processing-video/releases/download/latest/video-2.1.zip
          wget -O $LIB_DIR/controlP5.zip https://github.com/sojamo/controlp5/releases/download/v2.2.6/controlP5-2.2.6.zip
          wget -O $LIB_DIR/mqtt.zip https://github.com/256dpi/processing-mqtt/releases/download/v1.7.3/mqtt.zip
          wget -O $LIB_DIR/artnet4j.zip https://github.com/cansik/artnet4j/releases/download/0.6.2/artnet4j.zip
          unzip $LIB_DIR/artnet4j.zip -d $LIB_DIR
          mv $LIB_DIR/artnet4j-0.6.2 $LIB_DIR/artnet4j
          unzip $LIB_DIR/mqtt.zip -d $LIB_DIR
          unzip $LIB_DIR/video.zip -d $LIB_DIR
          unzip $LIB_DIR/controlP5.zip -d $LIB_DIR
          rm $LIB_DIR/*.zip
          rm $LIB_DIR/install_instructions.txt
          ls -l $LIB_DIR
          ls -l


