name: Export & create release

on:
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y default-jdk default-jre
          sudo apt-get install -y jq
          sudo apt-get install -y software-properties-common xvfb libxrender1 libxtst6 libxi6
          sudo apt-get install -y libsdl2-2.0-0

      - name: Download & Install Processing
        run: |
          wget https://github.com/processing/processing4/releases/download/processing-1276-4.0b1/processing-4.0b1-linux64.tgz
          tar -xvzf processing-4.0b1-linux64.tgz
          rm processing-4.0b1-linux64.tgz
          ls -l
          pwd